def image_repo = ''
def image_tag = ''

pipeline {
    agent any

    environment {
        PROJECT_ID = 'mobile-app-1-482109'
        CLUSTER = 'autopilot-cluster-1'
        ZONE = 'us-central1'
        
        // Update this path if your key is stored elsewhere
        GCP_KEY = '/var/lib/jenkins/keys/mobile-app-1-482109-e631e1327727.json'
        
        PYTHON_EXEC = 'python3.11'
        GIT_CREDENTIALS_ID = credentials('git-token-1')
    }

    stages {
        stage('Checkout with credentials') {
            steps {
                deleteDir()
                script {
                    withCredentials([string(credentialsId: 'git-token-1', variable: 'GIT_TOKEN')]) {
                        checkout([
                            $class: 'GitSCM',
                            branches: [[name: "*/dev"]],
                            userRemoteConfigs: [[
                                url: "https://${GIT_TOKEN}@github.com/kranthimj23/${env.microservice}.git"
                            ]]
                        ])
                    }
                }
            }
        }
                
        stage('Authenticate with GCP') {
            steps {
                withCredentials([file(credentialsId: 'gcp-key-1', variable: 'GCP_KEY_FILE')]) {
                    sh '''
                      gcloud auth activate-service-account --key-file="$GCP_KEY_FILE"
                      gcloud config set project mobile-app-1-482109
                      gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
                      gcloud auth list
                    '''
                }
            }
        }


        stage('Build Docker Image') {
            steps {
                script {
                    image_repo = "us-central1-docker.pkg.dev/${env.PROJECT_ID}/${env.microservice}/user"
                    image_tag = "${BUILD_NUMBER}-${env.env_namespace ?: 'dev'}" // fallback if env_namespace not set
                    def image_full = "${image_repo}:${image_tag}"

                    sh """
                        echo 'Logging in to Artifact Registry...'
                        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev

                        echo 'Building Docker image...'
                        docker build -t ${image_full} .

                        echo 'Pushing Docker image...'
                        docker push ${image_full}
                    """
                }
            }
        }

        stage('Deploy to GKE') {
            steps {
                sh """
                    gcloud container clusters get-credentials ${CLUSTER} --zone ${ZONE} --project ${PROJECT_ID}
                """

                configFileProvider([configFile(fileId: 'deploy_to_gke', targetLocation: 'deploy_to_gke.py')]) {
                    withCredentials([string(credentialsId: 'git-token-1', variable: 'GIT_TOKEN')]) {
                        script {
                            def pythonCommand = """
                                export CLUSTER=${CLUSTER}
                                export ZONE=${ZONE}
                                export PROJECT_ID=${PROJECT_ID}
                                echo Running Python script...
                                echo pwd
                                ${PYTHON_EXEC} deploy_to_gke.py ${env.env_namespace ?: 'dev'} ${image_repo} ${image_tag} ${env.github_url} ${env.microservice}
                            """
    
                            echo "Executing Python Deployment Script..."
    
                            def result = sh(script: pythonCommand, returnStdout: true).trim()
                            echo "Deployment Output:\n${result}"
                        }
                    }
                }
            }
        }
    }
}
